// <auto-generated />
using System;
using LunchPoll.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LunchPoll.Migrations
{
    [DbContext(typeof(LunchLocalContext))]
    partial class LunchLocalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LunchPoll.Models.LunchLocal", b =>
                {
                    b.Property<int>("LocalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("LocalId");

                    b.ToTable("LunchLocals");
                });

            modelBuilder.Entity("LunchPoll.Models.LunchVote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("Date");

                    b.Property<int>("LocalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("Date");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("VoteId");

                    b.HasIndex("LocalId");

                    b.ToTable("LunchVote");
                });

            modelBuilder.Entity("LunchPoll.Models.LunchVote", b =>
                {
                    b.HasOne("LunchPoll.Models.LunchLocal", "LunchLocal")
                        .WithMany("UsersVote")
                        .HasForeignKey("LocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LunchLocal");
                });

            modelBuilder.Entity("LunchPoll.Models.LunchLocal", b =>
                {
                    b.Navigation("UsersVote");
                });
#pragma warning restore 612, 618
        }
    }
}
